apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthsync-notifi-deployment
  labels:
    app: healthsync-notifi-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthsync-notifi-service
  template:
    metadata:
      labels:
        app: healthsync-notifi-service
    spec:
      containers:
        - name: healthsync-notifi-container
          image: your-dockerhub-username/healthsync-notifi-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_MAIL_HOST
              value: "smtp.gmail.com"
            - name: SPRING_MAIL_PORT
              value: "587"
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: username
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: password
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: healthsync-notifi-service
spec:
  type: LoadBalancer
  selector:
    app: healthsync-notifi-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083